[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/settings.py"]

[project]
name = "voicetovoic"
version = "0.0"
dependencies = [
    "pydantic-settings",
    "groq"
]
requires-python = ">=3.8"